export const projects = [
  {
    title: "AI-SDLC Framework",
    slug: "ai-sdlc-framework",
    description: `Experimental framework that adapts traditional Software Development Life Cycle (SDLC) principles for human-AI team collaboration, based on ISO 12207 standards.`,
    shortDescription: `Experimental framework for human-AI team collaboration in software development.`,
    href: "/projects/ai-sdlc-framework",
    externalUrl: "https://github.com/mouimet-infinisoft/AISDLC",
    mediaSrc: "/ai-sdlc.png",
    mediaType: "image",
    technologies: ["ISO 12207", "Software Engineering", "AI Collaboration", "SDLC"],
    status: "Active Development",
    year: "2024",
  },
  {
    title: "So Simple Platform",
    slug: "so-simple-platform",
    description: `Enterprise-grade web application for managing social service operations, built using voice-driven AI-SDLC methodology. Features multi-tenant architecture, workflow automation, and comprehensive case management.`,
    shortDescription: `Social services management platform built with voice-driven AI-SDLC methodology.`,
    href: "/projects/so-simple-platform",
    externalUrl: "https://github.com/mouimet-infinisoft/rqrsda2025",
    demoUrl: "https://sisimple.vercel.app/",
    mediaSrc: "/so-simple-card.png",
    mediaType: "image",
    technologies: ["Next.js 15", "React 19", "Supabase", "PostgreSQL", "Tailwind CSS", "N8N"],
    status: "MVP Ready",
    year: "2024",
  },
  {
    title: "iBrain Architecture",
    slug: "ibrain-architecture",
    description: `Open-source cognitive architecture for AI-driven applications. Features micro-apps, cognitive awareness, memory management, and theory of mind capabilities. Designed to revolutionize web interactions through AI with modular, scalable architecture.`,
    shortDescription: `Open-source cognitive architecture for AI-driven applications with advanced awareness capabilities.`,
    href: "/projects/ibrain-architecture",
    externalUrl: "https://github.com/ibrain-one/ibrain",
    demoUrl: "https://github.com/ibrain-one/ibrain/wiki",
    mediaSrc: "/ibrain-developer.png",
    mediaType: "image",
    technologies: ["Cognitive Architecture", "AI", "React", "TypeScript", "Micro-apps", "Memory Management"],
    status: "Open Source",
    year: "2024",
  },
  {
    title: "Brainstack Framework",
    slug: "brainstack-framework",
    description: `Collection of 30+ NPM packages designed for building AI-driven applications. Includes state management, event handling, logging, authentication, and cognitive tools. Provides modular, scalable solutions for complex application development.`,
    shortDescription: `30+ NPM packages for building AI-driven applications with advanced state management and cognitive tools.`,
    href: "/projects/brainstack-framework",
    externalUrl: "https://github.com/Infinisoft-inc/public/tree/ab88f9a669b12d6aac9b6f720a9f42b32f1684a4/Packages/%40brainstack",
    demoUrl: "https://www.npmjs.com/~infinisoft-world",
    mediaSrc: "/brainstack-framework.png",
    mediaType: "image",
    technologies: ["React", "TypeScript", "State Management", "Event Handling", "Authentication", "Logging", "NPM"],
    status: "Active Development",
    year: "2022",
  },

];
